name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,21,36,51 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
	curl -X POST \
	-d @post-body.xml
	https://hfdapp.houstontx.gov/JSONTest/WebService1.asmx --header "Content-Type:text/xml" | \
	xpath '//GetIncidentsResult/text()' | \
	jq > incidents.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
